# Generated by Django 3.1.5 on 2021-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.IntegerField()),
                ('turbility', models.IntegerField()),
                ('temperature', models.IntegerField()),
            ],
        ),
    ]
