# Generated by Django 3.1.5 on 2021-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='data',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ph',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='turbility',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
