# Generated by Django 3.1.5 on 2021-01-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210112_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='time'),
        ),
    ]
