# Generated by Django 3.1.5 on 2021-01-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210113_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='viewOnMap',
            field=models.BooleanField(default=False),
        ),
    ]
