# Generated by Django 3.1.5 on 2021-01-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_data_viewonmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('turbility', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='viewOnMap',
        ),
    ]
