# Generated by Django 3.1.5 on 2021-01-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_waypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abort', models.BooleanField(default=False)),
            ],
        ),
    ]
