# Generated by Django 3.1.7 on 2021-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_abort_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
    ]
