# Generated by Django 3.1.7 on 2021-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210319_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='voltage',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
    ]
