# Generated by Django 3.1.7 on 2021-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_data_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='automation',
            field=models.BooleanField(default=False),
        ),
    ]
